### ISSUE TITLE
Laghos fails with message -- unknown kernel -- higher order test with PA and higher order runs with -ok >= 8 fails with FA

### ISSUE THREAD

**Issue by cjoycd** [CEED/Laghos#179]
Dear all,

I was trying to test three-material, triple point problem using the following command.

mpirun -np 1 ./laghos -p 3 -m data/rectangle01_quad.mesh -rs 1 -tf 5.0 -pa -ok 5 -ot 4

and it shows the following error message and stops.

Unknown kernel 0x2a

MFEM abort: Unknown kernel
... in function: void mfem::hydrodynamics::QUpdate::UpdateQuadratureData(cont mfem::Vector&, mfem::hydrodynamics::QuadratureData&)
... in file: laghos_solver.cpp:1329

This happens when I choose PA and -ok greater than 4 (order of the kinematic field).

Similarly, with FA, for the same problem with -ok 8 -ot 7, it shows the following error.

Verification failed: (Q1D <= MQ) is false.
--> Quadrature rules more than 14 1D points are not supported! 
... in function: void mfem::internal::quadrature_interpolator::TensorValues(int, int, const mfem::DofToQuad&, const mfem::Vector&, mfem::Vector&) [with mfem::QVectorLayout::byVDIM]
... in file: fem/qinterp/eval_by_vdim.cpp:74

Please suggest..

Thank you in advance..

Sijoy C.D.

**Comment by vladotomov** [comment]
Hi Sijoy,

The first error happens because we don't have that kernel instance. You can get it running with this #180. You can add higher orders the same way.

The second verification is an MFEM restriction, see [here](https://github.com/mfem/mfem/blob/64c872559477c733c9bfc73aae6dc3e24b45b6f6/general/forall.hpp#L27-L33). You can create an MFEM issue and request more 1D quad points. I guess nobody has tried to run so high yet.

**Comment by vladotomov** [comment]
@cjoycd you can also try with https://github.com/mfem/mfem/pull/3722

**Comment by cjoycd** [comment]
Dear Vladimir,

Okay, I will follow the suggestions, thanks a lot…
